### PR TITLE
[JENKINS-48926] - Update Parent POM  and use “Publish Over” plugin with JEP-200 patches

### PR DESCRIPTION
**Pull request by oleg-nenashev**
https://issues.jenkins-ci.org/browse/JENKINS-48926. I confirmed that plugin PCT passes after the dependency update. 

@reviewbybees @jglick @slide

### CODE REVIEW

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by oleg-nenashev** [comment]
@rcgroot would it be possible to release it? JEP-200 has been released on Sunday, and it would be great to make the release available

**Comment by oleg-nenashev** [comment]
@rcgroot ping

**Comment by rcgroot** [comment]
I'll create a release in the coming days

**Comment by rcgroot** [comment]
Plugin update with this MR is released in 1.2.2

**Comment by oleg-nenashev** [comment]
Thanks a lot @rcgroot !

**Pull request merged**
